[package]
name = "trunk"
version = "0.1.0"
description = "Build, bundle & ship your Rust WASM application to the web."
license = "MIT/Apache-2.0"
authors = ["Anthony Dodd <dodd.anthonyjosiah@gmail.com>"]
edition = "2018"
repository = "https://github.com/thedodd/trunk"

[dependencies]
anyhow = "1.0.32"
async-std = { version="1.6.3", features=["attributes"] }
colored = "2.0.0"
grass = "0.10.3"
html-index = "0.3.4"
seahash = "4.0.1"
structopt = "0.3.16"
tide = "0.13.0"
