name: release
on:
  push:
    tags:
    - 'v*'

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          release_name: ""
          body: ""
          draft: true
          prerelease: false

  build:
    name: build
    runs-on: ${{ matrix.os }}
    needs: release
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            binName: x86_64-unknown-linux-gnu
            binPath: target/release/trunk
          - os: macos-latest
            binName: x86_64-apple-darwin
            binPath: target/release/trunk
          - os: windows-latest
            binName: x86_64-pc-windows-msvc
            binPath: target\release\trunk
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - uses: actions-rs/cargo@v1
        with:
          command: run
          args: --release -- -h
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: ${{ matrix.binPath }}
          asset_name: trunk-${{ matrix.binName }}
          asset_content_type: application/octet-stream
